var meetups = [
  { title: 'Taming the Technical Debt, HTML5 and the Magical Mobile App, and Isomorphic JS',
    date: new Date(2014, 2, 13, 18, 30),
    url: 'http://www.meetup.com/nychtml5/events/167187142/',
    speakers: [
      { title: 'Taming the Technical Debt',
        name: 'Brittany Storoz',
        twitter: 'brittanystoroz',
        desc: 'Committing hacky code is unavoidable at times, but when it becomes a habit rather than an exception, it breeds quickly.  How can we better handle the technical debt that creeps into our codebase before it gets out of control, and how can we heal a codebase that\'s already in the red? We\'ll talk about some strategies for keeping up with the clean up, without having to dedicate your day to maintenance. ' },
      { title: 'HTML5 and the Magical Mobile App',
        name: 'Mark Ludlow',
        desc: 'Hate Objective-C? Last coded Java in college? Why not build your App using the JavaScript you know and love?Here’s a demo of using Sencha Touch and Cordova (formerly PhoneGap) to build a mobile app that will almost magically run on multiple mobile platforms.' },
      { title: 'Isomorphic JavaScript',
        name: 'Michael Benin',
        twitter: 'michaelbenin',
        desc: 'Sharing JS between the client and server with browserify, also known as Isomorphic Javascript. Sharing routes, templating language, and templates in Backbone and Express to enable SEO in your SPA. Syncing events to media queries with EnquireJS to bind events conditionally to displayed styles. Investigations into Backbone-ORM with MongoDB/SQL, KeystoneJS CMS, PhoneGap Mobile Deployment, and Node-Webkit Desktop Deployment.' }]},
  { title : 'Matrix of Detection, Computer Vision in browser, Client Side Storage: IndexedDB',
    date: new Date(2014, 3, 16, 18, 30),
    url: 'http://www.meetup.com/nychtml5/events/170965392/',
    speakers: [
      { title: 'Matrix of Detection',
        name: 'Eric Shepherd',
        twitter: 'arkitrave',
        desc: 'Imagine a three-dimensional space created by X, Y, and Z axes. On the X axis, device detection determines the right quantity of code for the device; on the Y axis, resolution detection responds to the user\'s screen size; and on the Z axis, feature detection further tailors the experience to the browser\'s capabilities. With users located at points within this three-dimensional matrix, a single application can be served to everyone.' },
      { title: 'Computer vision and machine learning in the browser',
        name: 'Leonard Bogdonoff',
        twitter: 'rememberlenny',
        desc: 'A non-mathematician/non-pythonesta/beginner’s approach to HTML5 based javascript libraries that allow facial recognition, image content prediction, and other browser based machine learning/neural network application.' },
      { title: 'Overview of the HTML 5 client storage technologies',
        name: 'Deni Spasovski',
        twitter: 'denimf',
        desc: 'An introduction to the HTML 5 storage technologies: WebStorage, IndexedDB and WebSQL. Brief overview of their API’s and cross browser support of each of the technologies.' }]},
  { title: 'Exploring Chrome DevTools\' less used potential, Custom ESLint Rules, & Streams in a Browser',
    date: new Date(2014, 4, 14, 18, 30),
    url: 'http://www.meetup.com/nychtml5/events/177554272/',
    speakers: [
      { title: 'Exploring Chrome DevTools\' less used potential',
        name: 'Kirill Cherkashin',
        twitter: 'kirjs',
        desc: 'Often DevTools is used just for basic JavaScript debugging, but there is much more behind it than what is commonly used. In this talk we will go through an overview of some Chrome DevTools features, such as workspaces, snippets, shortcuts, extensions and several others. The goal is to showcase the less known and less used sides of Chrome DevTools so that we can make best use of what it can offer.' },
      { title: 'Custom ESLint Rules',
        name: 'Scott Weinstein',
        twitter: 'scottweinstein',
        desc: 'Why and how you can make your own rules for checking style, api usage, and more.' },
      { title: 'Streams in a Browser',
        name: 'Tom Buchok',
        twitter: 'tbuchok',
        desc: 'As client-side apps grows, we find ourselves pushing more and more data into the browser. Streaming data provides an approach that\'s resource-friendly for our programs and provides the end-user with a nicer experience. Let\'s take a look into streaming JSON and how it can work in the browser!' }] },
   { title: 'Amorphic, D3 in Ember, and Preloading Multimedia: Can Play Through?',
     date: new Date(2014, 5, 18, 18, 30),
     url: 'http://www.meetup.com/nychtml5/events/183102422/',
     speakers: [
       { title: 'Amorphic',
         name: 'Sam Elsamman',
         url: 'http://elsamman.com/',
         desc: 'Node.js creates a unique opportunity for applications to share a common structure on both the front-end and back-end.  Amorphic is a new isomorphic framework still under development that blurs the lines between browser and server letting the author focus on what is most important – the application itself.  In this talk we will get a preview of how Amorphic works by examining a simple application that uses it.' },
       { title: 'D3 in Ember',
         name: 'Heyjin Kim',
         twitter: 'heyjinkim',
         desc: 'D3 is a great library for data visualization, but when dealing with complex applications and DOM(SVG) manipulations are not fun. You can solve the problems with Ember. ' },
       { title: 'Preloading Multimedia: Can Play Through?',
         name: 'Denis Nazarov',
         twitter: 'literature',
         desc: 'As web applications incorporate more high quality multimedia assets, developers need a consistent way of knowing when video or audio has sufficiently loaded for uninterrupted playback to deliver a great user experience. This talk illustrates the inconsistencies of browser implementations of the "canplaythrough" event and proposes an alternative solution of determining preload progress based on the element\'s "buffered" property.' }] },
    { title: 'JS Debugging, Living with MediaQueries and Speed Up Thy Style',
      date: new Date(2014, 6, 16, 16, 30),
      url: 'http://www.meetup.com/nychtml5/events/183102422/',
      speakers: [
        { title: 'JS Debugging',
          name: 'Amjad Masad',
          twitter: 'amasad',
          desc: 'As the complexity of the apps we\'re building grows it becomes harder and harder to debug. Beyond your typical console.log and breakpoint insertion debugging I want to discuss some of the lesser known JS debugging techniques that has helped me debug some of the more elusive bugs I\'ve seen while working on Facebook.' },
        { title: 'Living with MediaQueries',
          name: 'Alex Lee',
          twitter: 'Aintaer',
          desc: 'Where most approaches to media queries relegate it to a CSS-only affair, coupling media queries to javascript managed views allows more divergent designs. At (Adobe) Behance, we grapple with mediaQuery, wrestle it into an event source, and use it to drive behavior-divergent pages.' },
        { title: 'Speed Up Thy Style',
          name: 'Shefali Pandey',
          twitter: 'shefalipandey',
          desc: 'As browsers evolve so do best practices for page performance. Some classics have endured like making fewer requests from CSS and writing concise semantic markup for faster rendering. And then there are some contentious performance grey areas like Data URIs (when to use? should they be used?), inline styles (are they faster than external styles? if yes, should one sacrifice readability for performance?), using SVGs for images, using CSS preprocessors (a battle between maintainability and performance?).' }]
     }
];

module.exports = meetups;
